version: 0.2

env:
  variables:
    TF_VERSION: "1.1.2"

phases:

  install:
    commands:
      - cd /usr/bin
      - "curl -s -qL -o terraform.zip https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip"
      - unzip -o terraform.zip

  pre_build:
    commands:
      - cd "$CODEBUILD_SRC_DIR"
      - terraform init -no-color
      - terraform validate
    
  build:
    commands:
      - terraform plan

  post_build:
    commands:
      - echo "terraform plan completed on `date`"